networks:
  httpsvc:
    name: httpsvc
    external: true
services:
  www:
    build: .
    container_name: www
    networks:
      - httpsvc
    volumes:
      - type: bind
        source: Caddyfile
        target: /etc/caddy/Caddyfile
      - www_config:/config
      - www_data:/data
    restart: unless-stopped
volumes:
  www_config:
  www_data:
    external: true
