services:
  www:
    build: .
    container_name: www
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - type: bind
        source: ./.well-known
        target: /usr/local/apache2/htdocs/.well-known
    restart: always
