services:
  www:
    build: .
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - type: bind
        source: ./ssl/server.crt
        target: /usr/local/apache2/ssl/server.crt
      - type: bind
        source: ./ssl/server.key
        target: /usr/local/apache2/ssl/server.key
      - type: bind
        source: ./.well-known
        target: /usr/local/apache2/htdocs/.well-known
      - type: bind
        source: ./.well-known
        target: /usr/local/apache2/gitweb/.well-known
      - type: bind
        source: ./git
        target: /usr/local/apache2/git
    restart: always
