networks:
  httpsvc:
    name: httpsvc
    external: true
services:
  www:
    build: .
    container_name: www
    networks:
      - httpsvc
    volumes:
      - type: bind
        source: ./.well-known
        target: /usr/local/apache2/htdocs/.well-known
    restart: always
