# SearXNG settings

use_default_settings: true

general:
  contact_url: "https://himbeerserver.de/md/contact.md"
  enable_metrics: true # TODO

search:
  default_lang: "de"

server:
  # Is overwritten by ${SEARXNG_SECRET}
  secret_key: "ultrasecretkey"
  limiter: false
  image_proxy: true
  # public URL of the instance, to ensure correct inbound links. Is overwritten
  # by ${SEARXNG_URL}.
  base_url: https://searxng.himbeerserver.de

ui:
  static_use_hash: true
  default_locale: "de"
  hotkeys: "vim"

# preferences:
#   lock:
#     - autocomplete
#     - method

enabled_plugins:
  - "Hash plugin"
  - "Self Informations"
  - "Tracker URL remover"
  - "Ahmia blacklist"
  # - "Hostnames plugin"  # see "hostnames" configuration below
  # - "Open Access DOI rewrite"

# plugins:
#   - only_show_green_results

hostnames:
  replace:
    '(.*\.)?youtube\.com$': 'iv.ggtyler.dev'
    '(.*\.)?youtu\.be$': 'iv.ggtyler.dev'
#   remove:
#     - '(.*\.)?facebook.com$'
  low_priority:
    - '(.*\.)?google\.com$'
#   high_priority:
#     - '(.*\.)?wikipedia.org$'

engines:

    - name: dictzone
      disabled: true

    - name: lingva
      disabled: true

    - name: "mymemory translated"
      disabled: true

    - name: translated
      disabled: true

    - name: google
      disabled: true

    - name: mojeek
      disabled: false

    - name: startpage
      disabled: false

    - name: wiby
      disabled: false

    - name: wolframalpha
      disabled: false

    - name: bahnhof
      disabled: false

    - name: "google images"
      disabled: true

    - name: "bing images"
      disabled: true

    - name: "duckduckgo images"
      disabled: false

    - name: "mojeek images"
      disabled: false

    - name: flickr
      disabled: true

    - name: "library of congress"
      disabled: true

    - name: pinterest
      disabled: true

    - name: unsplash
      disabled: true

    - name: wallhaven
      disabled: true

    - name: "bing videos"
      disabled: true

    - name: "google videos"
      disabled: true

    - name: "duckduckgo videos"
      disabled: false

    - name: vimeo
      disabled: true

    - name: youtube
      disabled: true

    - name: invidious
      disabled: false

    - name: "media.ccc.de"
      disabled: false

    - name: peertube
      disabled: false

    - name: "bing news"
      disabled: true

    - name: "google news"
      disabled: true

    - name: "yahoo news"
      disabled: true

    - name: tagesschau
      disabled: false

    - name: genius
      disabled: true

    - name: "radio browser"
      disabled: false

    - name: bandcamp
      disabled: true

    - name: mixcloud
      disabled: true

    - name: soundcloud
      disabled: true

    - name: "docker hub"
      disabled: true

    - name: hoogle
      disabled: true

    - name: pypi
      disabled: true

    - name: "alpine linux packages"
      disabled: false

    - name: "lib.rs"
      disabled: false

    - name: metacpan
      disabled: false

    - name: "pkg.go.dev"
      disabled: false

    - name: "caddy.community"
      disabled: false

    - name: codeberg
      disabled: false

    - name: gitlab
      disabled: false

    - name: sourcehut
      disabled: false

    - name: hackernews
      disabled: false

    - name: bt4g
      disabled: true

    - name: kickass
      disabled: true

    - name: piratebay
      disabled: true

    - name: solidtorrents
      disabled: true

    - name: "z-library"
      disabled: true

#   - name: fdroid
#     disabled: false
#
#   - name: apk mirror
#     disabled: false
#
#   - name: mediathekviewweb
#     categories: TV
#     disabled: false
#
#   - name: invidious
#     disabled: false
#     base_url:
#       - https://iv.ggtyler.dev
#       - https://invidious.privacyredirect.com
#       - https://invidious.jing.rocks
#       - https://invidious.perennialte.ch
#       - https://invidious.reallyaweso.me
#       - https://inv.tux.pizza
